### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lummy194** [aidhog/blabel#1]
Hello，Aidan Hogan！I am a chinese student. And I am studying how to detect the blank nodes in RDF recently. I run your code, but failed. 
I run the Main.java, its error is
        "usage: cl.uchile.dcc.blabel.cli.Main
        missing <utility> arg where <utility> one of
	LabelRDFGraph: Run labelling over an RDF graph encoded as N-Triples
	RunNQuadsTest: [Testing] Compute the canonical graphs in a quads file
	Control: [Testing] Run a control experiment to time parsing a quads file
	RunSyntheticEvaluation: [Testing] Run synthetic benchmark"
 I don't know how to solve it, now i was so upset that i can't move forward. I really hope you can help me. Thanks for your time sincerely and wait for your response.

**Comment by aidhog** [comment]
Hi! You need to select which utility you want to run. Probably you want to select LabelRDFGraph and then select from the options it shows. See here for more options: http://blabel.github.io/
